version: '3.3'

services:
  db:
    image: mysql:8
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-CHANGEME}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-CHANGEME}
      MYSQL_USER: ${MYSQL_USER:-CHANGEME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-CHANGEME}

  wordpress:
    depends_on:
      - db
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./wordpress:/var/www/html
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST:-db}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER:-CHANGEME}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD:-CHANGEME}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME:-CHANGEME}
      DOMAIN: ${DOMAIN:-CHANGEME}
      EMAIL: ${EMAIL:-CHANGEME}
      SMTP_HOST: ${SMTP_HOST:-CHANGEME}
      SMTP_PORT: ${SMTP_PORT:-587}
      SMTP_USER: ${SMTP_USER:-CHANGEME}
      SMTP_PASS: ${SMTP_PASS:-CHANGEME}
      SMTP_SECURE: ${SMTP_SECURE:-on}
      SMTP_ACCOUNT: ${SMTP_ACCOUNT:-default}


  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: ${PMA_HOST:-db}
      PMA_PORT: ${PMA_PORT:-3306}
      PMA_USER: ${PMA_USER:-CHANGEME}
      PMA_PASSWORD: ${PMA_PASSWORD:-CHANGEME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-CHANGEME}
